# Generated by Django 4.2.23 on 2025-08-12 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_method', models.CharField(choices=[('upi', 'UPI/Net Banking'), ('qr', 'QR Pay')], max_length=10)),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='payments/')),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
    ]
