# Generated by Django 4.2.23 on 2025-08-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_player_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='preferred_time',
            field=models.CharField(blank=True, choices=[('after_10_am', 'After 10 AM'), ('after_1_pm', 'After 1 PM'), ('after_4_pm', 'After 4 PM'), ('after_8_pm', 'After 8 PM')], max_length=20, null=True),
        ),
    ]
